version: '3.8'

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - .env/:/app/.env
      - ./files:/app/files
    command: make run
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: miniapp
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  app:
    image: node:latest
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "npm install && npm run build"
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf
      - ./app/dist:/usr/share/nginx/html
      - ./files:/usr/share/nginx/files
      - ./static:/usr/share/nginx/static
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
      - db

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: always
