version: '3.8'

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - .env/:/app/.env
    ports:
      - 3001:3001
    command: make run
    depends_on:
      - db
  
  app:
    image: node:latest
    command: npm run dev 
    volumes:
      - ./admin_dashboard:/app
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0

  db:
    image: postgres
    environment:
      POSTGRES_DB: miniapp
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/dist:/usr/share/nginx/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
      - db

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: always
